FROM public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py310-sdk2.25.1-ubuntu22.04

# This image already includes the upstreaming-to-vllm neuron-2.25 fork.
# Reference: https://github.com/aws-neuron/upstreaming-to-vllm/tree/neuron-2.25

ENV VLLM_NEURON_FRAMEWORK=neuronx-distributed-inference

COPY ../start-vllm.sh /app/start-vllm.sh
RUN chmod +x /app/start-vllm.sh

ENV MODEL="meta-llama/Llama-3.3-70B-Instruct"
ENV PORT="8000"
ENV MAX_NUM_SEQS="8"
ENV MAX_MODEL_LEN="8192"
ENV TENSOR_PARALLEL_SIZE="64"
ENV VLLM_DEVICE="neuron"
ENV SPECULATIVE_MAX_MODEL_LEN="8192"
ENV OVERRIDE_NEURON_CONFIG="{}"
ENV ENABLE_TOOL_CALLING="false"
ENV ENABLE_PREFIX_CACHING="false"
ENV ENABLE_KV_TRANSFER="false"
ENV KV_CONNECTOR="NeuronConnector"
ENV KV_BUFFER_SIZE="2e11"
ENV ETCD=""
ENV CONFIG_FILE=""

CMD ["/app/start-vllm.sh"]
